# Generated by Django 4.1.7 on 2023-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('FrontEnd WEB', 'FrontEnd WEB'), ('BackEnd WEB', 'BackEnd WEB'), ('Data Science', 'Data Science'), ('Data Analysis', 'Data Analysis'), ('Mobile Dev', 'Mobile Dev'), ('UI/UX', 'UI/UX'), ('Others', 'Others')], default='Others', max_length=200),
        ),
    ]
