# Generated by Django 4.1.7 on 2023-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_alter_directmessage_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='messengers',
            field=models.ManyToManyField(through='chatapp.DirectMessage', to='chatapp.inbox'),
        ),
    ]
